cp -r /home/luis/.config/polybar/* /home/luis/github/linux/config/.config/polybar/
cp -r /home/luis/.config/i3/* /home/luis/github/linux/config/.config/i3/
cp -r /home/luis/.config/alacritty/* /home/luis/github/linux/config/.config/alacritty/
cp -r /home/luis/.config/rofi/* /home/luis/github/linux/config/.config/rofi/
cp -r /home/luis/.config/nvim/* /home/luis/github/linux/config/.config/nvim/
cp -r /home/luis/.config/picom.conf /home/luis/github/linux/config/.config/
cp -r /home/luis/.xmodmap /home/luis/github/linux/config/
cp -r /home/luis/.touchpad_disable.sh /home/luis/github/linux/config/
cp -r /home/luis/.Xresources /home/luis/github/linux/config/
